// Code generated by go-swagger; DO NOT EDIT.

package job

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"ridhodinar/dans-tes/models"
)

// GetJobDetailOKCode is the HTTP code returned for type GetJobDetailOK
const GetJobDetailOKCode int = 200

/*
GetJobDetailOK Job Detail

swagger:response getJobDetailOK
*/
type GetJobDetailOK struct {

	/*
	  In: Body
	*/
	Payload *models.JobDetail `json:"body,omitempty"`
}

// NewGetJobDetailOK creates GetJobDetailOK with default headers values
func NewGetJobDetailOK() *GetJobDetailOK {

	return &GetJobDetailOK{}
}

// WithPayload adds the payload to the get job detail o k response
func (o *GetJobDetailOK) WithPayload(payload *models.JobDetail) *GetJobDetailOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get job detail o k response
func (o *GetJobDetailOK) SetPayload(payload *models.JobDetail) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetJobDetailOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetJobDetailBadRequestCode is the HTTP code returned for type GetJobDetailBadRequest
const GetJobDetailBadRequestCode int = 400

/*
GetJobDetailBadRequest Bad Request

swagger:response getJobDetailBadRequest
*/
type GetJobDetailBadRequest struct {
}

// NewGetJobDetailBadRequest creates GetJobDetailBadRequest with default headers values
func NewGetJobDetailBadRequest() *GetJobDetailBadRequest {

	return &GetJobDetailBadRequest{}
}

// WriteResponse to the client
func (o *GetJobDetailBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// GetJobDetailNotFoundCode is the HTTP code returned for type GetJobDetailNotFound
const GetJobDetailNotFoundCode int = 404

/*
GetJobDetailNotFound Jobs Not Found

swagger:response getJobDetailNotFound
*/
type GetJobDetailNotFound struct {
}

// NewGetJobDetailNotFound creates GetJobDetailNotFound with default headers values
func NewGetJobDetailNotFound() *GetJobDetailNotFound {

	return &GetJobDetailNotFound{}
}

// WriteResponse to the client
func (o *GetJobDetailNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// GetJobDetailInternalServerErrorCode is the HTTP code returned for type GetJobDetailInternalServerError
const GetJobDetailInternalServerErrorCode int = 500

/*
GetJobDetailInternalServerError Server error

swagger:response getJobDetailInternalServerError
*/
type GetJobDetailInternalServerError struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetJobDetailInternalServerError creates GetJobDetailInternalServerError with default headers values
func NewGetJobDetailInternalServerError() *GetJobDetailInternalServerError {

	return &GetJobDetailInternalServerError{}
}

// WithPayload adds the payload to the get job detail internal server error response
func (o *GetJobDetailInternalServerError) WithPayload(payload string) *GetJobDetailInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get job detail internal server error response
func (o *GetJobDetailInternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetJobDetailInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
