// Code generated by go-swagger; DO NOT EDIT.

package job

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetAllJobsHandlerFunc turns a function with the right signature into a get all jobs handler
type GetAllJobsHandlerFunc func(GetAllJobsParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAllJobsHandlerFunc) Handle(params GetAllJobsParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetAllJobsHandler interface for that can handle valid get all jobs params
type GetAllJobsHandler interface {
	Handle(GetAllJobsParams, interface{}) middleware.Responder
}

// NewGetAllJobs creates a new http.Handler for the get all jobs operation
func NewGetAllJobs(ctx *middleware.Context, handler GetAllJobsHandler) *GetAllJobs {
	return &GetAllJobs{Context: ctx, Handler: handler}
}

/*
	GetAllJobs swagger:route GET /job job getAllJobs

Get All job
*/
type GetAllJobs struct {
	Context *middleware.Context
	Handler GetAllJobsHandler
}

func (o *GetAllJobs) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetAllJobsParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
