// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// JobDetail job detail
//
// swagger:model JobDetail
type JobDetail struct {

	// company
	Company string `json:"company,omitempty"`

	// company logo
	CompanyLogo string `json:"company_logo,omitempty"`

	// company url
	CompanyURL string `json:"company_url,omitempty"`

	// created at
	CreatedAt string `json:"created_at,omitempty"`

	// description
	Description string `json:"description,omitempty"`

	// how to apply
	HowToApply string `json:"how_to_apply,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// location
	Location string `json:"location,omitempty"`

	// title
	Title string `json:"title,omitempty"`

	// type
	Type string `json:"type,omitempty"`

	// url
	URL string `json:"url,omitempty"`
}

// Validate validates this job detail
func (m *JobDetail) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this job detail based on context it is used
func (m *JobDetail) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *JobDetail) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *JobDetail) UnmarshalBinary(b []byte) error {
	var res JobDetail
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
